### ISSUE TITLE
Please clarify "Assertion/Failure Features" portion of the README

### ISSUE THREAD

**Issue by MisterScott** [christianhujer/aceunit#20]
I would appreciate clarification of the "Assertion/Failure Features" portion of the README file.  The table under "there are multiple ways how you can make a test-case fail" has entries for Assertion + Runner pairs, with entries of ["yes", "no", "stop", "no (not required)"].  

Could you please clarify what each entry option means?  Initial guess is that the table entries for each Assertion + Runner pair mean:
- "no":  this Assertion condition (e.g. use of `longjmp()` with SimpleRunner) will _not_ result in a test case fail (for that Runner)
- "yes":  this Assertion _will_ result in a test case fail
- "stop":  this Assertion will cause unit testing to _stop_
- "no (not required)":  this Assertion will _not_ result in a test case fail, however I don't understand what "(not required)" could mean here?

Thanks in advance!

Version:  AceUnit-3, commit 4071c93.

**Comment by christianhujer** [comment]
Great question. I will add a clarification to the README.md.

**Comment by christianhujer** [comment]
Fixed.
