### ISSUE TITLE
comments for basic and basicEmbedded might be mixed up

### ISSUE THREAD

**Issue by w1res** [christianhujer/aceunit#3]
I am looking at the `RunTests.c` files in the `test\basic` and `test\basicEmbedded`. If you look at the file comments on line 28, it seems that the comments might be mixed up between the two files.

For example, in the `test\basic` folder it says the following:

    /** Test executor for AceUnit unit test "basicEmbedded".

but in `test\basicEmbedded` it says

    /** Test executor for AceUnit unit test "basic".

I am still learning this framework, so I am not sure if anything else in the files is mixed up as well, or if it is just those comments.

**Comment by w1res** [comment]
I think I was just confused about how something works.

**Comment by christianhujer** [comment]
Actually you're right, thanks for pointing that out. Thus, I reopen it.
