### ISSUE TITLE
aceunit claims to support C89/C90, but requires multiple C99 features

### ISSUE THREAD

**Issue by winspool** [christianhujer/aceunit#8]
Some  main files require C99:
* aceunit.h uses the predefined macro "\_\_func\_\_", which is a C99 feature

* aceunit.h is including '<stdbool.h>', which is a C99 header

* aceunit.h is using the 'bool' type, which is a C23 feature (or with <stdbool.h> a C99 feature) 

* AceUnit_SetJmpRunner.c mixes declarations and code, which is not allowed in C90

* additional warnings from 'clang' for most files:
  "warning: a function declaration without a prototype is deprecated in all versions of C"

Most selftest source files require C99
(probably all of them, but i didn't check that):

* the predefined macro "\_\_func\_\_" is used in many locations

* 'bool' is used in many locations

I used for testing:

```
CC=gcc  CFLAGS="-Wall -pedantic -std=c89" 

or

CC=clang  CFLAGS="-Wall -pedantic -std=c89" 
```

**Comment by christianhujer** [comment]
Fixed all of that. Thanks for reporting.
